name: Java Home Maven Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Copy via ssh
      uses: garygrossgarten/github-action-scp@v0.5.3
      with:
        # Path to the local folder you want to copy.
        local: target/webapp.war
        # Path on the remote server to copy to.
        remote: /opt/tomcat8/webapps/hari.war
        # Number of concurrent file transfers.
        host: 13.232.216.31
        # Username for authentication.
        username: ec2-user
        privateKey: ${{ secrets.tomcatKey }}
        # Password for password-based user authentication.
